### PR TITLE
package as namespace

### PR DESCRIPTION
**Pull request by dyk**

### CODE REVIEW

**Comment by bradcfisher** [comment]
Looks like the dependency on org.gnieh.diffson should only be for the tests?  For example:

libraryDependencies += "org.gnieh" %% "diffson" % "1.0.0" % "test"

**Comment by bradcfisher** [comment]
I'm also wondering whether this is strictly necessary.  Per the Avro spec, a "name" attribute with a period in it will be treated as a full name and the namespace and name can be extracted from it.  Perhaps it could be a configurable behavior whether to include the fullname in "name" or split into "name" and "namespace"?

**Comment by dyk** [comment]
You're right. Diffson should be in the test scope. Fixed

**Comment by dyk** [comment]
Package as namespace is not necessary. I changed that to be consistent with other types: AvroEnum, AvroJEnum etc. I think it's to small for configuration. Other libraries should handle either way.

**Comment by bradcfisher** [comment]
Agreed.  I didn't realize it was being done inconsistently.  I've merged the pull request.

**Pull request merged**
